
---
apiVersion: batch/v1
kind: Job
metadata:
  name: training-automl-{{ experiment_name }}
  namespace: kubeflow
spec:
  parallelism: 2
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: training-automl-{{ experiment_name }}
      annotations:
        tf-version.cloud-tpus.google.com: "2.11.0"
    spec:
      containers:
      - name: training-container
        image: tensorflow/tensorflow:2.11.0
        resources:
          limits:
            cloud-tpus.google.com/preemptible-v2: 8
        command:
        - /bin/sh
        - -c
        - |
          apt-get update && apt-get install git -y
          pip install redis cloud-tpu-client google-cloud-storage mlflow==2.2.2
          cd /tf/notebooks
          python3 worker_automl.py --redis_host=redis --queue_name=automl
        volumeMounts:
        - mountPath: "/tf/notebooks"
          name: ml-service-automl
        env:
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: uri
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: username
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: password
          - name: MLFLOW_EXPERIMENT_NAME
            value: {{ experiment_name }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: credential-file
          - name: REDIS_SERVICE_HOST
            value: redis
          - name: MODEL_DIR
            value: pixelbrain
      volumes:
      - name: ml-service-automl
        persistentVolumeClaim:
          claimName: ml-service-pvc
      restartPolicy: OnFailure