
---
apiVersion: batch/v1
kind: Job
metadata:
  name: training-pretrained-{{ experiment_name }}
  namespace: kubeflow
spec:
  parallelism: 4
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 86400
  template:
    metadata:
      name: training-pretrained-{{ experiment_name }}
      annotations:
        tf-version.cloud-tpus.google.com: "2.11.0"
    spec:
      containers:
      - name: training-container
        image: mailnophone03/mlops:latest
        imagePullPolicy: Always
        resources:
          limits:
            cloud-tpus.google.com/preemptible-v2: 8
        command:
        - /bin/sh
        - -c
        - |
          python3 /tf/notebooks/worker.py --redis_host=redis --queue_name=job2
        env:
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: uri
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: username
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: password
          - name: MLFLOW_EXPERIMENT_NAME
            value: {{ experiment_name }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: credential-file
          - name: BACKEND_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: backend-service
          - name: REDIS_SERVICE_HOST
            value: redis
          - name: MODEL_DIR
            value: pixelbrain/models
      restartPolicy: OnFailure
