apiVersion: batch/v1
kind: Job
metadata:
  name: training-pretrained-{{ experiment_name }}
  namespace: kubeflow
spec:
  parallelism: 2
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: training-pretrained-{{ experiment_name }}
      annotations:
        tf-version.cloud-tpus.google.com: "2.11.0"
    spec:
      containers:
      - name: training-container
        image: tensorflow/tensorflow:2.11.0
        resources:
          limits:
            cloud-tpus.google.com/preemptible-v2: 8
        command:
        - /bin/sh
        - -c
        - |
          apt-get update && apt-get install git -y
          pip install redis cloud-tpu-client google-cloud-storage mlflow==2.2.2
          cd /tf/notebooks
          python3 worker.py --redis_host=redis --queue_name=job2
        volumeMounts:
        - mountPath: "/tf/notebooks"
          name: ml-service
        env:
          - name: MLFLOW_TRACKING_URI
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: uri
          - name: MLFLOW_TRACKING_USERNAME
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: username
          - name: MLFLOW_TRACKING_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: password
          - name: MLFLOW_EXPERIMENT_NAME
            value: example_experiment
          - name: GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: credential-file
          - name: REDIS_SERVICE_HOST
            value: redis
          - name: MODEL_DIR
            value: uet-mlflow
      volumes:
      - name: ml-service
        persistentVolumeClaim:
          claimName: ml-service-pvc
      restartPolicy: OnFailure
---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: nas-{{ experiment_name }}
spec:
  parallelTrialCount: 5
  maxTrialCount: 20
  maxFailedTrialCount: 10
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-Accuracy
  algorithm:
    algorithmName: enas
  nasConfig:
    graphConfig:
      numLayers: 20
      inputSizes:
        - {{ target_size }}
        - {{ target_size }}
        - 3
      outputSizes:
        - {{ num_classes }}
    operations:
      - operationType: convolution
        parameters:
          - name: filter_size
            parameterType: categorical
            feasibleSpace:
              list:
                - "3"
                - "5"
                - "7"
          - name: num_filter
            parameterType: categorical
            feasibleSpace:
              list:
                - "32"
                - "48"
                - "64"
                - "96"
                - "128"
          - name: stride
            parameterType: categorical
            feasibleSpace:
              list:
                - "1"
                - "2"
      - operationType: separable_convolution
        parameters:
          - name: filter_size
            parameterType: categorical
            feasibleSpace:
              list:
                - "3"
                - "5"
                - "7"
          - name: num_filter
            parameterType: categorical
            feasibleSpace:
              list:
                - "32"
                - "48"
                - "64"
                - "96"
                - "128"
          - name: stride
            parameterType: categorical
            feasibleSpace:
              list:
                - "1"
                - "2"
          - name: depth_multiplier
            parameterType: categorical
            feasibleSpace:
              list:
                - "1"
                - "2"
      - operationType: depthwise_convolution
        parameters:
          - name: filter_size
            parameterType: categorical
            feasibleSpace:
              list:
                - "3"
                - "5"
                - "7"
          - name: stride
            parameterType: categorical
            feasibleSpace:
              list:
                - "1"
                - "2"
          - name: depth_multiplier
            parameterType: categorical
            feasibleSpace:
              list:
                - "1"
                - "2"
      - operationType: reduction
        parameters:
          - name: reduction_type
            parameterType: categorical
            feasibleSpace:
              list:
                - max_pooling
                - avg_pooling
          - name: pool_size
            parameterType: int
            feasibleSpace:
              min: "2"
              max: "3"
              step: "1"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: neuralNetworkArchitecture
        description: NN architecture contains operations ID on each NN layer and skip connections between layers
        reference: architecture
      - name: neuralNetworkConfig
        description: Configuration contains NN number of layers, input and output sizes, description what each operation ID means
        reference: nn_config
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: mailnophone03/automl:katib
                imagePullPolicy: Always
                command:
                  - python3
                  - -u
                  - RunTrial.py
                  - --num_epochs=100
                  - --architecture="${trialParameters.neuralNetworkArchitecture}"
                  - --nn_config="${trialParameters.neuralNetworkConfig}"
                  - --dataset_url={{ dataset_url }}
                  - --target_size={{ target_size }}
                env:
                - name: REDIS_SERVICE_HOST
                  value: "redis"
                - name: QUEUE_NAME
                  value: "automl"
                - name: MLFLOW_TRACKING_URI
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-secret
                      key: uri
                - name: MLFLOW_TRACKING_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-secret
                      key: username
                - name: MLFLOW_TRACKING_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-secret
                      key: password
                - name: MLFLOW_EXPERIMENT_NAME
                  value: example_experiment
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-secret
                      key: credential-file
            restartPolicy: Never