apiVersion: v1
kind: Secret
metadata:
  namespace: kubeflow
  name: app-secret
type: Opaque
data:
  backend-service: aHR0cHM6Ly9hcGkucGl4ZWxicmFpbi5udnF1eW5oLmNvZGVz # https://api.pixelbrain.nvquynh.codes
  frontend-service: aHR0cHM6Ly9waXhlbGJyYWluLm52cXV5bmguY29kZXM= # https://pixelbrain.nvquynh.codes
  ml-service: aHR0cHM6Ly9tbC5waXhlbGJyYWluLm52cXV5bmguY29kZXM= # https://ml.pixelbrain.nvquynh.codes