apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
type: Opaque
data:
  uri: aHR0cHM6Ly9tbGZsb3ctZ2NwLTc0bXF2ZjVobmEtdWMuYS5ydW4uYXBw # https://mlflow.nvquynh.codes
  username: bWxmbG93 # mlflow
  password: bWxmbG93 # mlflow
  credential-file: L3RmL25vdGVib29rcy9jcmVkZW50aWFscy5qc29u # /tf/notebooks/credentials.json
