---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-service
spec:
  storageClassName: "apps"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: ml-service-pvc
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-service-pvc
spec:
  storageClassName: "apps"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  containers:
    - name: master
      image: redis:latest
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
type: Opaque
data:
  uri: aHR0cHM6Ly9tbGZsb3ctZ2NwLTc0bXF2ZjVobmEtdWMuYS5ydW4uYXBw # https://mlflow.nvquynh.codes
  username: bWxsb3c= # mlflow
  password: bWxsb3c= # mlflow
  credential-file: L3RmL25vdGVib29rcy9jcmVkZW50aWFscy5qc29u # /tf/notebooks/credentials.json
---
apiVersion: v1
kind: Pod
metadata:
  name: push-job
spec:
  restartPolicy: Never
  containers:
  - name: push-job-container
    image: python:3.8.16-alpine
    command:
    - /bin/sh
    - -c
    - |
      pip3 install redis argparse
      echo "Pushing jobs to queue..."
      python3 /mnt/job.py --redis_host=redis --queue_name=job2
    volumeMounts:
    - name: volume-pvc
      mountPath: "/mnt"
  volumes:
  - name: volume-pvc
    persistentVolumeClaim:
      claimName: ml-service-pvc